fullscreen=true # toggle with F11, KeyCode 300
fps=144 # 0, 2147483647 ; if < 0 highest possible fps
gameCursor=false # false = use os cursor
lang="TH" # in ./assets/langs/{folder_name} ; can fetch in game
debug=false 

[window]
title = "The Game"
width=1600
height=900
flag=0x00000004 

[keymap] # no controller support yet
up = 87 # w 
down = 83 # s
left = 65 # a
right = 68 # d
in = 81 # q
out = 69 # e
confirm = 257 # enter
cancel = 340 # left shift
back = 259 # backspace or mouse 4 
forward = 92 # backslash or mouse 5 
close = 259 # esc

[sound]# 0,100
main=0 
music=100 
action=100 
environment=100
people=100
animal=100
