debug = false
gameCursor = false
fullscreen = true
fps = 60
lang = 'TH'

[sound]
main = 0
music = 100
action = 100
environment = 100
people = 100
animal = 100

[window]
flag = 4
width = 1600
height = 900
title = 'The Game'

[keymap]
up = 87
down = 83
left = 65
right = 68
in = 81
out = 69
confirm = 257
cancel = 340
back = 259
forward = 92
close = 259
